name       : virt-manager
version    : 3.2.0
release    : 28
source     :
    - https://virt-manager.org/download/sources/virt-manager/virt-manager-3.2.0.tar.gz : 2b6fe3d90d89e1130227e4b05c51e6642d89c839d3ea063e0e29475fd9bf7b86
license    : GPL-2.0-or-later
summary    : Manage virtual machines with virt-manager
component  : virt
description: |
    The virt-manager application is a desktop user interface for managing virtual machines through libvirt. It primarily targets KVM VMs, but also manages Xen and LXC (linux containers). It presents a summary view of running domains, their live performance & resource utilization statistics. Wizards enable the creation of new domains, and configuration & adjustment of a domain’s resource allocation & virtual hardware. An embedded VNC and SPICE client viewer presents a full graphical console to the guest domain.
builddeps  :
    - libgtk-3
    - python-docutils
rundeps    :
    - gtk-vnc
    - libgtksourceview4
    - libosinfo
    - libvirt-glib
    - libvirt-python
    - libvte
    - python-requests
    - qemu
    - spice
    - spice-gtk
    - virglrenderer
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -f $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
    rm -f $installdir/usr/share/icons/hicolor/icon-theme.cache
