name       : virt-manager
version    : 1.2.1
release    : 1
source     :
    - https://virt-manager.org/download/sources/virt-manager/virt-manager-1.2.1.tar.gz : 74bba80e72e5e1b4d84f1d5b7211b874e9c4ae00a0a44149d1721acab38ce6be
license    : GPL-2.0
summary    : Manage virtual machines with virt-manager
description: |
    The virt-manager application is a desktop user interface for managing virtual machines through libvirt. It primarily targets KVM VMs, but also manages Xen and LXC (linux containers). It presents a summary view of running domains, their live performance & resource utilization statistics. Wizards enable the creation of new domains, and configuration & adjustment of a domain’s resource allocation & virtual hardware. An embedded VNC and SPICE client viewer presents a full graphical console to the guest domain.
builddeps  :
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libuser)
    - pkgconfig(libvirt)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(yajl)
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
