name       : virt-manager
version    : 2.0.0
release    : 18
source     :
    - https://github.com/virt-manager/virt-manager/archive/v2.0.0.tar.gz : 2ac0a26e486b26d62150d2fb749c0401cfd87c78419a0f05d3634889b045a7ad
license    : GPL-2.0-or-later
summary    : Manage virtual machines with virt-manager
component  : virt
description: |
    The virt-manager application is a desktop user interface for managing virtual machines through libvirt. It primarily targets KVM VMs, but also manages Xen and LXC (linux containers). It presents a summary view of running domains, their live performance & resource utilization statistics. Wizards enable the creation of new domains, and configuration & adjustment of a domain’s resource allocation & virtual hardware. An embedded VNC and SPICE client viewer presents a full graphical console to the guest domain.
builddeps  :
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libuser)
    - pkgconfig(libvirt)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(yajl)
rundeps    :
    - gtk-vnc
    - libosinfo
    - libvirt-glib
    - libvirt-python
    - libvte
    - python-requests
    - qemu
    - spice-gtk
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -f $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
    rm -f $installdir/usr/share/icons/hicolor/icon-theme.cache
