name       : virt-manager
version    : 1.4.3
release    : 11
source     :
    - https://releases.pagure.org/virt-manager/virt-manager-1.4.3.tar.gz : 528226b9a0fdd6cd66451a8217fc7c87f3deb6bebd08599c25fe5c7291fe6a24
license    : GPL-2.0
summary    : Manage virtual machines with virt-manager
component  : virt
description: |
    The virt-manager application is a desktop user interface for managing virtual machines through libvirt. It primarily targets KVM VMs, but also manages Xen and LXC (linux containers). It presents a summary view of running domains, their live performance & resource utilization statistics. Wizards enable the creation of new domains, and configuration & adjustment of a domain’s resource allocation & virtual hardware. An embedded VNC and SPICE client viewer presents a full graphical console to the guest domain.
builddeps  :
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libuser)
    - pkgconfig(libvirt)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(yajl)
rundeps    :
    - gtk-vnc
    - libosinfo
    - libvirt-python
    - libvirt-glib
    - libvte
    - python-ipaddr
    - qemu
    - spice-gtk
build      : |
    %python_setup
install    : |
    %python_install
    rm -f $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
    rm -f $installdir/usr/share/icons/hicolor/icon-theme.cache
