name       : virt-manager
version    : 2.0.0
release    : 17
source     :
    - https://releases.pagure.org/virt-manager/virt-manager-2.0.0.tar.gz : eb6fa4d7b7d539fb006d0822760a5e97ddf99b1f131806d08eaea6d4f3ea88ac
license    : GPL-2.0-or-later
summary    : Manage virtual machines with virt-manager
component  : virt
description: |
    The virt-manager application is a desktop user interface for managing virtual machines through libvirt. It primarily targets KVM VMs, but also manages Xen and LXC (linux containers). It presents a summary view of running domains, their live performance & resource utilization statistics. Wizards enable the creation of new domains, and configuration & adjustment of a domain’s resource allocation & virtual hardware. An embedded VNC and SPICE client viewer presents a full graphical console to the guest domain.
builddeps  :
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libuser)
    - pkgconfig(libvirt)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(yajl)
rundeps    :
    - gtk-vnc
    - libosinfo
    - libvirt-glib
    - libvirt-python
    - libvte
    - python-requests
    - qemu
    - spice-gtk
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -f $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
    rm -f $installdir/usr/share/icons/hicolor/icon-theme.cache
