name       : virt-manager
version    : 2.2.1
release    : 23
source     :
    - https://github.com/virt-manager/virt-manager/archive/v2.2.1.tar.gz : 708146fa0c101d686553c8daf170bf9ce43fb6176bbf90c685e653a291d248c5
license    : GPL-2.0-or-later
summary    : Manage virtual machines with virt-manager
component  : virt
description: |
    The virt-manager application is a desktop user interface for managing virtual machines through libvirt. It primarily targets KVM VMs, but also manages Xen and LXC (linux containers). It presents a summary view of running domains, their live performance & resource utilization statistics. Wizards enable the creation of new domains, and configuration & adjustment of a domain’s resource allocation & virtual hardware. An embedded VNC and SPICE client viewer presents a full graphical console to the guest domain.
builddeps  :
    - libgtk-3
rundeps    :
    - gtk-vnc
    - libgtksourceview
    - libosinfo
    - libvirt-glib
    - libvirt-python
    - libvte
    - python-requests
    - qemu
    - spice
    - spice-gtk
    - virglrenderer
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -f $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
    rm -f $installdir/usr/share/icons/hicolor/icon-theme.cache
