name       : virt-manager
version    : 3.0.0
release    : 27
source     :
    - https://github.com/virt-manager/virt-manager/archive/v3.0.0.tar.gz : bc934c748395e98ed02e225898acefffc3464067873c9508fee5321b77a5f718
license    : GPL-2.0-or-later
summary    : Manage virtual machines with virt-manager
component  : virt
description: |
    The virt-manager application is a desktop user interface for managing virtual machines through libvirt. It primarily targets KVM VMs, but also manages Xen and LXC (linux containers). It presents a summary view of running domains, their live performance & resource utilization statistics. Wizards enable the creation of new domains, and configuration & adjustment of a domain’s resource allocation & virtual hardware. An embedded VNC and SPICE client viewer presents a full graphical console to the guest domain.
builddeps  :
    - libgtk-3
    - python-docutils
rundeps    :
    - gtk-vnc
    - libgtksourceview
    - libosinfo
    - libvirt-glib
    - libvirt-python
    - libvte
    - python-requests
    - qemu
    - spice
    - spice-gtk
    - virglrenderer
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -f $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
    rm -f $installdir/usr/share/icons/hicolor/icon-theme.cache
